# Generated by Django 6.0.4 on 2026-04-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda', 'boda boda')], max_length=50)),
                ('day_rate', models.IntegerField()),
                ('night_rate', models.IntegerField()),
                ('short', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=25)),
                ('number_plate', models.CharField(max_length=6)),
                ('model_color', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('nin', models.CharField(max_length=14)),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('rate', models.CharField(choices=[('day', 'Day'), ('night', 'night'), ('short', 'Short')], max_length=20)),
                ('status', models.CharField(choices=[('parked', 'Parked'), ('signed_out', 'Signed_Out')], max_length=20)),
                ('type', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory')),
            ],
        ),
    ]
