# Generated by Django 6.0.4 on 2026-04-26 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='model_color',
            new_name='model',
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='departure_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='driver_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='number_plate',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='rate',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'night'), ('short', 'Short')], max_length=20, null=True),
        ),
    ]
