# Generated by Django 6.0.4 on 2026-04-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_vehicleregistration_receiver_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='receiver_contact',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='receiver_nin',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='signed_out_by',
        ),
    ]
