# Generated by Django 6.0.4 on 2026-05-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_vehicleregistration_receiver_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
