# Generated by Django 6.0.4 on 2026-05-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_vehicleregistration_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
