# Generated by Django 6.0.4 on 2026-05-31 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_vehicleregistration_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSignOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=12)),
                ('receiver_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('receiver_nin', models.CharField(max_length=14)),
                ('exit_date', models.DateField(auto_now_add=True)),
                ('exit_time', models.TimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signouts', to='parking.vehicleregistration')),
            ],
        ),
    ]
