# Generated by Django 6.0.4 on 2026-04-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_tyreservice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batteryservice',
            name='battery_type',
        ),
        migrations.AddField(
            model_name='batteryservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.serviceprice'),
        ),
        migrations.AlterField(
            model_name='batteryservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='name',
            field=models.CharField(choices=[('pressure', 'Tyre Pressure'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement'), ('battery_hire', 'Battery Hire'), ('battery_sale', 'Battery Sale')], max_length=20),
        ),
    ]
