# Generated by Django 6.0.4 on 2026-04-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_batteryservice_battery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='category',
            field=models.CharField(choices=[('tyre', 'Tyre'), ('battery', 'Battery')], default='tyre', max_length=10),
            preserve_default=False,
        ),
    ]
