# Generated by Django 6.0.4 on 2026-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceprice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='category',
            field=models.CharField(choices=[('tyre', 'Tyre'), ('battery', 'Battery')], default='tyre', max_length=10),
        ),
    ]
