# Generated by Django 6.0.4 on 2026-04-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_serviceprice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryservice',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='service.serviceprice'),
            preserve_default=False,
        ),
    ]
